# Use Node.js image as the base
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the client code
COPY client/ .

# Build the React app
RUN npm run build

# Expose the port
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]