version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./AIVLE_Backend:/app/AIVLE_Backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here  # 환경 변수 추가

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REACT_APP_BACKEND_URL=http://host.docker.internal:8000
      - REACT_APP_SOCKETIO_URL=http://host.docker.internal:5000

  socketio:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python AIVLE_Backend/socketio_server/server.py
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_KEY=<your-openai-api-key> #add it here
      - KAKAO_API_KEY=<your-kakao-api-key> #add it here
      - NAVER_API_KEY=<your-NAVER-api-key> #add it here

networks:
  app-network:
    driver: bridge
