# Generated by Django 5.0.6 on 2024-07-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="신고 날짜")),
                ("category", models.CharField(max_length=255, verbose_name="사건 분류")),
                ("location", models.CharField(max_length=255, verbose_name="사건 발생 장소")),
                ("details", models.TextField(null=True, verbose_name="구체적인 현장 상태")),
                (
                    "address_name",
                    models.CharField(max_length=255, null=True, verbose_name="추정 주소"),
                ),
                (
                    "place_name",
                    models.CharField(max_length=255, null=True, verbose_name="추정 장소"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, null=True, verbose_name="전화번호"),
                ),
                ("full_text", models.TextField(null=True, verbose_name="전체 신고 기록")),
                (
                    "is_duplicate",
                    models.BooleanField(default=False, verbose_name="중복 신고 여부"),
                ),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[("emergency", "구급"), ("non_emergency", "비구급")],
                        max_length=15,
                        verbose_name="구급 여부",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
