# Generated by Django 4.2.13 on 2024-07-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stt", "0003_calllogs_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllogs",
            name="jurisdiction",
            field=models.CharField(max_length=32, null=True, verbose_name="관할서"),
        ),
        migrations.AddField(
            model_name="calllogs",
            name="lat",
            field=models.FloatField(null=True, verbose_name="위도"),
        ),
        migrations.AddField(
            model_name="calllogs",
            name="lng",
            field=models.FloatField(null=True, verbose_name="경도"),
        ),
        migrations.AddField(
            model_name="emergencycalls",
            name="lat",
            field=models.FloatField(null=True, verbose_name="위도"),
        ),
        migrations.AddField(
            model_name="emergencycalls",
            name="lng",
            field=models.FloatField(null=True, verbose_name="경도"),
        ),
    ]
