# Generated by Django 4.2.13 on 2024-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("disaster_large", models.CharField(max_length=10)),
                ("disaster_medium", models.CharField(max_length=10)),
                ("urgency_level", models.CharField(max_length=10)),
                ("sentiment", models.CharField(max_length=10)),
                ("symptom", models.CharField(max_length=100, null=True)),
                ("triage", models.CharField(max_length=100, null=True)),
                ("text", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
