# Generated by Django 4.2.13 on 2024-07-26 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_active",
        ),
    ]
